# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page3.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.showMaximized()
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.nick = QtWidgets.QComboBox(self.centralwidget)
        self.nick.setObjectName("nick")
        self.nick.addItem("")
        self.nick.addItem("")
        self.nick.addItem("")
        self.nick.addItem("")
        self.gridLayout.addWidget(self.nick, 0, 0, 1, 1)
        self.ip = QtWidgets.QComboBox(self.centralwidget)
        self.ip.setObjectName("ip")
        self.ip.addItem("")
        self.ip.addItem("")
        self.ip.addItem("")
        self.ip.addItem("")
        self.gridLayout.addWidget(self.ip, 0, 1, 1, 1)
        self.tcp = QtWidgets.QComboBox(self.centralwidget)
        self.tcp.setObjectName("tcp")
        self.tcp.addItem("")
        self.tcp.addItem("")
        self.tcp.addItem("")
        self.gridLayout.addWidget(self.tcp, 1, 0, 1, 2)
        self.nick_2 = QtWidgets.QComboBox(self.centralwidget)
        self.nick_2.setObjectName("nick_2")
        self.nick_2.addItem("")
        self.nick_2.addItem("")
        self.nick_2.addItem("")
        self.nick_2.addItem("")
        self.gridLayout.addWidget(self.nick_2, 2, 0, 1, 1)
        self.ip_2 = QtWidgets.QComboBox(self.centralwidget)
        self.ip_2.setObjectName("ip_2")
        self.ip_2.addItem("")
        self.ip_2.addItem("")
        self.ip_2.addItem("")
        self.ip_2.addItem("")
        self.gridLayout.addWidget(self.ip_2, 2, 1, 1, 1)
        self.tcp_2 = QtWidgets.QComboBox(self.centralwidget)
        self.tcp_2.setObjectName("tcp_2")
        self.tcp_2.addItem("")
        self.tcp_2.addItem("")
        self.tcp_2.addItem("")
        self.gridLayout.addWidget(self.tcp_2, 3, 0, 1, 2)
        self.nick_3 = QtWidgets.QComboBox(self.centralwidget)
        self.nick_3.setObjectName("nick_3")
        self.nick_3.addItem("")
        self.nick_3.addItem("")
        self.nick_3.addItem("")
        self.nick_3.addItem("")
        self.gridLayout.addWidget(self.nick_3, 4, 0, 1, 1)
        self.ip_3 = QtWidgets.QComboBox(self.centralwidget)
        self.ip_3.setObjectName("ip_3")
        self.ip_3.addItem("")
        self.ip_3.addItem("")
        self.ip_3.addItem("")
        self.ip_3.addItem("")
        self.gridLayout.addWidget(self.ip_3, 4, 1, 1, 1)
        self.tcp_3 = QtWidgets.QComboBox(self.centralwidget)
        self.tcp_3.setObjectName("tcp_3")
        self.tcp_3.addItem("")
        self.tcp_3.addItem("")
        self.tcp_3.addItem("")
        self.gridLayout.addWidget(self.tcp_3, 5, 0, 1, 2)
        self.main = QtWidgets.QPushButton(self.centralwidget)
        self.main.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"background-color: rgb(0, 255, 0);\n"
"border: 2px solid #555;\n"
"border-radius: 20px;\n"
"border-style: outset;\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.main.setObjectName("main")
        self.gridLayout.addWidget(self.main, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(528, 410))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Capture (1).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1536, 39))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.main.clicked.connect(self.goback)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nick.setItemText(0, _translate("MainWindow", "Nickname"))
        self.nick.setItemText(1, _translate("MainWindow", "Nickname1"))
        self.nick.setItemText(2, _translate("MainWindow", "Nickname2"))
        self.nick.setItemText(3, _translate("MainWindow", "Nickname3"))
        self.ip.setItemText(0, _translate("MainWindow", "IP ADDRESS"))
        self.ip.setItemText(1, _translate("MainWindow", "IP ADDRESS 1"))
        self.ip.setItemText(2, _translate("MainWindow", "IP ADDRESS 2"))
        self.ip.setItemText(3, _translate("MainWindow", "IP ADDRESS 3"))
        self.tcp.setItemText(0, _translate("MainWindow", "*display TCP dump data here"))
        self.tcp.setItemText(1, _translate("MainWindow", "*display TCP dump data here 1"))
        self.tcp.setItemText(2, _translate("MainWindow", "*display TCP dump data here 2"))
        self.nick_2.setItemText(0, _translate("MainWindow", "Nickname"))
        self.nick_2.setItemText(1, _translate("MainWindow", "Nickname1"))
        self.nick_2.setItemText(2, _translate("MainWindow", "Nickname2"))
        self.nick_2.setItemText(3, _translate("MainWindow", "Nickname3"))
        self.ip_2.setItemText(0, _translate("MainWindow", "IP ADDRESS"))
        self.ip_2.setItemText(1, _translate("MainWindow", "IP ADDRESS 1"))
        self.ip_2.setItemText(2, _translate("MainWindow", "IP ADDRESS 2"))
        self.ip_2.setItemText(3, _translate("MainWindow", "IP ADDRESS 3"))
        self.tcp_2.setItemText(0, _translate("MainWindow", "*display TCP dump data here"))
        self.tcp_2.setItemText(1, _translate("MainWindow", "*display TCP dump data here 1"))
        self.tcp_2.setItemText(2, _translate("MainWindow", "*display TCP dump data here 2"))
        self.nick_3.setItemText(0, _translate("MainWindow", "Nickname"))
        self.nick_3.setItemText(1, _translate("MainWindow", "Nickname1"))
        self.nick_3.setItemText(2, _translate("MainWindow", "Nickname2"))
        self.nick_3.setItemText(3, _translate("MainWindow", "Nickname3"))
        self.ip_3.setItemText(0, _translate("MainWindow", "IP ADDRESS"))
        self.ip_3.setItemText(1, _translate("MainWindow", "IP ADDRESS 1"))
        self.ip_3.setItemText(2, _translate("MainWindow", "IP ADDRESS 2"))
        self.ip_3.setItemText(3, _translate("MainWindow", "IP ADDRESS 3"))
        self.tcp_3.setItemText(0, _translate("MainWindow", "*display TCP dump data here"))
        self.tcp_3.setItemText(1, _translate("MainWindow", "*display TCP dump data here 1"))
        self.tcp_3.setItemText(2, _translate("MainWindow", "*display TCP dump data here 2"))
        self.main.setText(_translate("MainWindow", "Main Menu"))

    def goback(self):
        MainWindow.close()
        os.system("python page1.py")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
